import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
 
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-sans", // this will override your --font-sans in CSS
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GrowthOps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased scroll-smooth snap-y snap-mandatory overflow-y-scroll h-screen`}>
         {children}
      </body>
    </html>
  );
}
